version: '3.7'

services:
  app:
    container_name: expenseDRFAPI
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./incomeExpenseDRFApi/.env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    env_file:
      - ./incomeExpenseDRFApi/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A incomeExpenseDRFApi worker -l info
    volumes:
      - .:/app
    env_file:
      - ./incomeExpenseDRFApi/.env
    depends_on:
      - db
      - redis
      - app
volumes:
  pgdata:

